'use client';

import { Shield, AlertCircle, CheckCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

export function NoAIGuarantee() {
  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-8 border border-indigo-200">
      <div className="max-w-4xl mx-auto">
        <div className="flex flex-col lg:flex-row items-center gap-8">
          {/* Badge Section */}
          <div className="text-center lg:text-left">
            <div className="inline-flex items-center gap-3 mb-4">
              <div className="bg-indigo-600 text-white rounded-full p-4">
                <Shield className="h-10 w-10" />
              </div>
              <div>
                <h2 className="text-3xl font-bold text-gray-900">100% Human Reviews</h2>
                <Badge className="bg-white/80 text-indigo-700 border-indigo-300 px-3 py-1 mt-2">
                  No AI • No Bots • Real People Only
                </Badge>
              </div>
            </div>
          </div>

          {/* Guarantee Details */}
          <div className="flex-1 space-y-4">
            <div className="bg-white/80 backdrop-blur rounded-xl p-6 border border-indigo-200">
              <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                <AlertCircle className="h-5 w-5 text-indigo-600" />
                Our "No AI" Guarantee
              </h3>
              <p className="text-gray-700 mb-4">
                Every review on Verdict is written by a real human. If you suspect any feedback was generated by AI, 
                report it and we&apos;ll investigate immediately.
              </p>
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <p className="text-sm font-semibold text-green-800 flex items-center gap-2">
                  <CheckCircle className="h-4 w-4" />
                  If we find AI-generated content: Full refund + 2 free credits
                </p>
              </div>
            </div>

            {/* How We Ensure This */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
              <div className="bg-white/60 rounded-lg p-4 text-center">
                <div className="font-semibold text-gray-900 mb-1">Verified Judges</div>
                <p className="text-gray-600">Real profiles with reputation scores</p>
              </div>
              <div className="bg-white/60 rounded-lg p-4 text-center">
                <div className="font-semibold text-gray-900 mb-1">Quality Checks</div>
                <p className="text-gray-600">AI detection on every submission</p>
              </div>
              <div className="bg-white/60 rounded-lg p-4 text-center">
                <div className="font-semibold text-gray-900 mb-1">Human Touch</div>
                <p className="text-gray-600">Personal experiences & empathy</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}